export const en = {
  // Tabs
  'tab.today': 'Today',
  'tab.people': 'People',
  'tab.health': 'Health',
  'tab.card': 'My Card',
  'tab.settings': 'Settings',

  // Health labels
  'health.warm': 'Warm',
  'health.cooling': 'Cooling',
  'health.atRisk': 'At risk',
  'health.cold': 'Cold',

  // Categories
  'category.professional': 'Professional',
  'category.friend': 'Friend',
  'category.family': 'Family',
  'category.mentor': 'Mentor',
  'category.client': 'Client',
  'category.other': 'Other',

  // Relative time
  'time.today': 'today',
  'time.tomorrow': 'tomorrow',
  'time.yesterday': 'yesterday',
  'time.inDays': 'in {n} days',
  'time.daysAgo': '{n} days ago',
  'time.monthAgo': 'a month ago',
  'time.monthsAgo': '{n} months ago',
  'time.yearAgo': 'a year ago',
  'time.yearsAgo': '{n} years ago',

  // Shared
  'common.back': 'Back',
  'common.save': 'Save',
  'common.cancel': 'Cancel',
  'common.delete': 'Delete',
  'common.lastTouch': 'last touch {when}',

  // Today
  'today.title': 'The right moment,\nthe right move.',
  'today.teaser.badge': '{count} moments waiting',
  'today.teaser.headline':
    'Someone in your circle has a birthday this week. Someone else is about to go cold.',
  'today.teaser.body':
    'Call Your Mom watches for the right occasion — a birthday, a promise coming due, a relationship drifting — and hands you the exact move with the message already drafted.',
  'today.teaser.cta': 'Unlock the nudge engine',
  'today.empty.allWarm':
    'Nothing needs you today. Every relationship you track is warm — go enjoy it.',
  'today.empty.noContacts':
    'No one to reconnect with yet. Add the people you care about and the right moments will show up here.',
  'today.section.worthActingOn': 'Worth acting on',
  'today.section.whenMinute': 'When you have a minute',
  'today.capture': 'Capture someone you just met',

  // People
  'people.title': 'People',
  'people.search': 'Search people or companies',
  'people.import': 'Import from your address book',
  'people.importing': 'Importing…',
  'people.section.needsAttention': 'Needs attention',
  'people.section.doingFine': 'Doing fine',
  'people.empty.title': 'No people yet',
  'people.empty.body':
    'Capture someone you just met, or import your address book to get started.',
  'people.import.imported': 'Imported {count} contacts',
  'people.import.importedBody':
    'They came in without context — add why each one matters when you get a chance.',
  'people.import.nothing': 'Nothing new to import',
  'people.sync': 'Sync contacts',
  'people.syncing': 'Syncing…',
  'people.sync.result': '{imported} in, {exported} out',
  'people.sync.upToDate': 'Contacts up to date',

  // Nudge card
  'nudge.kind.moment': 'The moment',
  'nudge.kind.drifting': 'Drifting',
  'nudge.writeIt': 'Write it',
  'nudge.snooze': 'Snooze',
  'nudge.notNow': 'Not now',

  // Nudge content (generated by the engine, resolved at render time)
  'nudgec.birthday.headline': "It's {name}'s birthday 🎂",
  'nudgec.birthday.reason': 'Their birthday is right around the corner.',
  'nudgec.birthday.action.family': 'Call {name} to wish them a happy birthday',
  'nudgec.birthday.action.pro': 'Send {name} a birthday note and suggest catching up',
  'nudgec.commitment.headline': 'You made {name} a promise',
  'nudgec.commitment.reason': 'You committed: {commitment}',
  'nudgec.commitment.action': 'Deliver on it: "{commitment}"',
  'nudgec.reconnect.headline': '{months} months since you met {name}',
  'nudgec.reconnect.reason.where': 'You met at {where}',
  'nudgec.reconnect.reason.generic': 'A natural moment to resurface',
  'nudgec.reconnect.action.where': 'Send a "been thinking of you" note — mention {where}',
  'nudgec.reconnect.action.generic': 'Send {name} a short "been thinking of you" note',
  'nudgec.decay.headline': '{name} is drifting',
  'nudgec.decay.reason': 'No contact in {days} days — your rhythm is every {cadence}',
  'nudgec.decay.action.family': 'Give {name} a quick call',
  'nudgec.decay.action.friend': 'Text {name} something that reminded you of them',
  'nudgec.decay.action.pro': 'Send {name} a short check-in note',

  // Notifications
  'notify.digest.title': '{count} moments worth acting on',
  'notify.digest.body': 'Starting with: {action}',
  'notify.birthday.title': "It's {name}'s birthday 🎂",
  'notify.birthday.body': 'A good day to reach out. Open the app for a ready draft.',

  // Draft fallback templates (used when no AI key/proxy is configured)
  'draft.signoff': 'Warmly,',
  'draft.tpl.birthday.family':
    "Happy birthday, {name}!! Calling you later today — don't let me catch you screening. Love you.",
  'draft.tpl.birthday.pro':
    "Happy birthday, {name}! Hope you're celebrating properly. It's been too long — would love to catch up soon and hear how things are going.",
  'draft.tpl.commitment':
    'Hi {name} — following up on what I promised: {commitment}. Making it happen this week — more soon.',
  'draft.tpl.reconnect.where':
    'Hi {name} — you crossed my mind today. It has been a while since {where}. How have you been? Would love to catch up.',
  'draft.tpl.checkin.casual': "Hey {name} — thinking of you. It's been too long. Call this week?",
  'draft.tpl.checkin.pro':
    'Hi {name} — it has been a while and I wanted to check in. How have things been on your end? Would be great to catch up soon.',

  // Dashboard
  'dashboard.title': 'Relationship health',
  'dashboard.gate.headline': 'See which relationships are quietly going cold',
  'dashboard.gate.body':
    'The aging dashboard sorts everyone you know into warm, cooling, at-risk, and cold — so nothing dies of neglect.',
  'dashboard.gate.cta': 'Unlock with Pro',
  'dashboard.bringBack': 'Bring these back to warm',
  'dashboard.empty': "Everyone is warm or cooling. That's the whole game — keep it up.",
  'dashboard.emptyNoContacts': 'Add people and their health will show up here.',

  // Card
  'card.title': 'My card',
  'card.subtitle': 'Let them scan it — any camera app adds you straight to their contacts.',
  'card.share.subtitle':
    'Scanning opens your card page — they can save you and share their details right back.',
  'card.share.rotate': 'New link',
  'card.share.rotateConfirm': 'Tap again — the old QR stops working',
  'card.mode.link': 'Scans open your card page',
  'card.mode.vcard': 'Scans save your contact directly — sign in to get your card page',
  'card.edit': 'Edit details',
  'card.editHeading': 'Edit card',
  'card.save': 'Save card',

  // Personas
  'persona.title': 'Personas',
  'persona.subtitle':
    'Each persona is its own relationship graph — its own people, card, and rhythms.',
  'persona.switcher.title': 'Viewing as',
  'persona.switcher.manage': 'Manage personas',
  'persona.new': 'New persona',
  'persona.save': 'Save',
  'persona.cancel': 'Cancel',
  'persona.default': 'Default',
  'persona.active': 'Active',
  'persona.use': 'Switch to',
  'persona.setDefault': 'Make default',
  'persona.delete': 'Delete',
  'persona.deleteConfirm': 'Really delete?',
  'persona.deleteBody': 'Its people move to your default persona. Tap again to confirm.',
  'persona.contactCount': '{n} people',

  // Exchange inbox
  'inbox.title': 'From your card · {n}',
  'inbox.accept': 'Add',
  'inbox.viaCard': 'Shared their details via your QR',

  // Share landing page (public)
  'share.brand': 'Call Your Mom',
  'share.notFound': "This card link isn't active anymore. Ask for a fresh one.",
  'share.unavailable': "This card can't be loaded right now.",
  'share.save': 'Save {name} to contacts',
  'share.exchange.title': 'Share yours back',
  'share.exchange.body': "Leave your details and {name} will have them the next time they open the app.",
  'share.exchange.note': 'Anything worth remembering? (where you met, what you talked about)',
  'share.exchange.submit': 'Share my details',
  'share.exchange.sending': 'Sending…',
  'share.exchange.thanksTitle': 'Sent',
  'share.exchange.thanks': '{name} will have your details the next time they open the app.',
  'share.exchange.error': "That didn't go through — try again.",

  // Fields
  'field.name': 'Name',
  'field.tagline': 'Tagline',
  'field.firstName': 'First name',
  'field.lastName': 'Last name',
  'field.email': 'Email',
  'field.phone': 'Phone',
  'field.company': 'Company',
  'field.role': 'Role',
  'field.city': 'City',
  'field.birthday': 'Birthday (MM-DD, if you know it)',

  // Capture
  'capture.step0.title': 'Who did you meet?',
  'capture.next.context': 'Next: the context',
  'capture.step1.title': "Capture it while it's fresh",
  'capture.step1.body':
    'This is the part every other app skips — and the fuel for every future nudge.',
  'capture.field.whereMet': 'Where did you meet?',
  'capture.field.discussed': 'What did you discuss?',
  'capture.field.whyMatters': 'Why do they matter?',
  'capture.field.commitment': 'What did you commit to?',
  'capture.field.whereMet.ph': 'The founder dinner at...',
  'capture.field.commitment.ph': 'Intro them to...',
  'capture.due.label': 'When is it due?',
  'capture.due.tomorrow': 'Tomorrow',
  'capture.due.in3days': 'In 3 days',
  'capture.due.nextWeek': 'Next week',
  'capture.next.keep': 'Next: how to keep them',
  'capture.step2.title': 'How should we keep this warm?',
  'capture.category.label': 'Category',
  'capture.importance.label': 'How much do they matter?',
  'importance.1': 'Keep around',
  'importance.2': 'Important',
  'importance.3': 'Inner circle',
  'capture.cadence.label': 'Stay in touch every…',
  'cadence.days': '{n} days',
  'cadence.month': 'month',
  'cadence.2months': '2 months',
  'cadence.quarter': 'quarter',
  'cadence.6months': '6 months',
  'capture.cadence.suggestion': 'Suggested for {category}: every {n} days',
  'capture.save': 'Save contact',

  // Contact detail
  'contact.notFound': 'Contact not found.',
  'contact.logTouchpoint': 'Log a touchpoint',
  'log.call': 'Call',
  'log.text': 'Text',
  'log.email': 'Email',
  'log.coffee': 'Coffee',
  'log.met': 'Met',
  'log.meeting': 'Meeting',
  'contact.context.title': 'The context',
  'contact.context.whereMet': 'Where you met',
  'contact.context.discussed': 'What you discussed',
  'contact.context.whyMatters': 'Why they matter',
  'contact.committedTo': 'You committed to: {commitment}',
  'contact.committedDue': 'You committed to: {commitment} — due {date}',
  'contact.context.empty':
    'No context captured. The next time you talk, jot down why this person matters — future-you will thank you.',
  'contact.history': 'History',
  'contact.noHistory': 'No interactions logged yet.',
  'contact.edit': 'Edit',
  'contact.delete': 'Delete contact',
  'contact.delete.confirm': 'Delete {name}?',
  'contact.delete.confirmBody':
    'This removes them and all their context and history. This cannot be undone.',
  'contact.cadenceEvery': 'every {n} days',

  // Edit contact
  'edit.title': 'Edit contact',
  'edit.context.title': 'The context',
  'edit.save': 'Save changes',

  // Nudge composer
  'compose.notFound': 'Nudge not found.',
  'compose.channel.text': 'Text',
  'compose.channel.text.disabled': 'Text (no number)',
  'compose.channel.email': 'Email',
  'compose.channel.email.disabled': 'Email (no address)',
  'compose.yourDraft': 'Your draft',
  'compose.source.ai': 'Drafted from your notes',
  'compose.source.template': 'Drafted from your notes',
  'compose.writing': 'Writing from what you captured…',
  'compose.openMail': 'Open in Mail',
  'compose.openMessages': 'Open in Messages',
  'compose.markSent': 'Mark as sent',

  // Paywall
  'paywall.headline': 'Remembering is hard.\nSo we do it for you.',
  'paywall.body':
    'Capturing contacts is free, forever. Pro is the intelligence layer: it watches for the right moment and hands you the move.',
  'paywall.feature.nudges.title': 'Occasion-aware nudges',
  'paywall.feature.nudges.body':
    'Birthdays, promises coming due, relationships drifting — surfaced at the right moment, with the right move.',
  'paywall.feature.drafts.title': 'Messages, half-written',
  'paywall.feature.drafts.body':
    'Every nudge comes with a draft built from the context you captured — edit and send.',
  'paywall.feature.dashboard.title': 'The aging dashboard',
  'paywall.feature.dashboard.body':
    'See exactly which relationships are warm, cooling, at risk, or cold.',
  'paywall.feature.personas.title': 'Personas',
  'paywall.feature.personas.body':
    'Separate graphs for founder you, day-job you, personal you — each with its own card, people, and rhythms.',
  'paywall.feature.email.title': 'Email sync (coming first to Gmail)',
  'paywall.feature.email.body':
    'Last-contact dates stay accurate without logging anything by hand.',
  'paywall.price': '$99 / year',
  'paywall.priceSub': 'One rekindled relationship pays for a decade of this.',
  'paywall.cta': 'Go Pro',
  'paywall.fine': "No ads. Ever. Your relationships aren't for sale.",

  // Onboarding
  'onboarding.welcome.eyebrow': 'Welcome to Call Your Mom',
  'onboarding.welcome.title': 'Keep the relationships you\ncare about from going cold.',
  'onboarding.welcome.body':
    'Capture the people you meet with the context of why they matter — and we tell you the right moment and the right move to reconnect.',
  'onboarding.welcome.cta': 'Get started',
  'onboarding.card.title': 'Set up your card',
  'onboarding.card.body':
    'This is what you share when you meet someone. You can change it anytime.',
  'onboarding.card.cta': 'Continue',
  'onboarding.card.skip': 'Skip for now',
  'onboarding.notify.title': 'Never miss the moment',
  'onboarding.notify.body':
    'We send a quiet nudge when there is a real reason to reach out — a birthday, a promise coming due. No spam, ever.',
  'onboarding.notify.enable': 'Turn on reminders',
  'onboarding.notify.later': 'Maybe later',
  'onboarding.start.title': 'Add your first person',
  'onboarding.start.body': 'Start with someone who matters. Or explore with sample data.',
  'onboarding.start.capture': 'Add someone',
  'onboarding.start.import': 'Import my contacts',
  'onboarding.start.sample': 'Explore with sample data',

  // Settings
  'settings.title': 'Settings',
  'settings.personas': 'Manage personas',
  'settings.section.profile': 'Your profile',
  'settings.section.notifications': 'Notifications',
  'settings.section.subscription': 'Subscription',
  'settings.section.language': 'Language',
  'settings.section.privacy': 'Privacy',
  'settings.section.data': 'Your data',
  'settings.notifications.label': 'Reminders for the right moments',
  'settings.notifications.web': 'Reminders are available in the mobile app.',
  'settings.notifications.needsPro': 'Reminders come with Pro.',
  'settings.subscription.pro': 'Pro — active',
  'settings.subscription.proBody': 'Thank you for supporting an app with no ads.',
  'settings.subscription.free': 'Free plan',
  'settings.subscription.upgrade': 'Upgrade to Pro',
  'settings.privacy.statement':
    'We never sell your data and never show ads. Your relationships are yours. Email and calendar connections sync only timestamps and participants — never message contents.',
  'settings.data.export': 'Export my data',
  'settings.data.exported': 'Data ready',
  'settings.data.sample': 'Load sample data',
  'settings.data.reset': 'Delete everything',
  'settings.data.reset.confirm': 'Delete everything?',
  'settings.data.reset.confirmBody':
    'This permanently removes all contacts, context, and history from this device.',
  'settings.editProfile': 'Edit profile',

  // Sync / account
  'settings.section.account': 'Account & sync',
  'settings.account.signedInAs': 'Synced as {email}',
  'settings.account.syncBody': 'Your relationships back up securely and sync across devices.',
  'settings.account.signOut': 'Sign out',
  'settings.account.signIn': 'Sign in to sync across devices',
  'settings.account.localOnly': 'Saved on this device only.',

  // Auth screen
  'auth.title': 'Sync your circle',
  'auth.subtitle': 'Create an account to back up your relationships and use Call Your Mom on every device.',
  'auth.signIn': 'Sign in',
  'auth.or': 'or',
  'auth.continueWithApple': 'Continue with Apple',
  'auth.continueWithGoogle': 'Continue with Google',
  'auth.webOnlyNote': 'Accounts are created in the app. Sign in with the email you used there.',
  'auth.signUp': 'Create account',
  'auth.password': 'Password',
  'auth.working': 'Working…',
  'auth.checkEmail': 'Check your email to confirm your account, then sign in.',
  'auth.error': 'Something went wrong. Try again.',
  'auth.privacyNote': 'We only store your relationship data — never message contents. No ads, ever.',

  // Gmail sync
  'settings.section.gmail': 'Email sync',
  'gmail.connect': 'Connect Gmail',
  'gmail.connected': 'Gmail connected: {email}',
  'gmail.body': 'We read only timestamps and participants to keep "last contact" accurate — never the contents of your emails.',
  'gmail.syncNow': 'Sync now',
  'gmail.syncing': 'Syncing…',
  'gmail.disconnect': 'Disconnect',
  'gmail.connecting': 'Connecting…',
  'gmail.synced': 'Synced {count} new interactions',
  'gmail.syncedNone': 'Up to date',
  'gmail.error': "Couldn't connect Gmail. Try again.",
  'gmail.needsAccount': 'Sign in first to connect Gmail.',
  'gmail.mobileOnly': 'Email sync runs in the mobile app.',
} as const;
